name: Build

on:
    push:
        branches: [ "master" ]

jobs:
    build:
        
        runs-on: ubuntu-latest
        
        steps:
            -   uses: actions/checkout@v4
            -   name: Use Node.js ${{ matrix.node-version }}
                uses: actions/setup-node@v4
            -   name: Increment value
                uses: yoichiro/gh-action-increment-value@main
                with:
                    target_directory: '.'
                    target_file: 'version.json'
                    prefix: 'buildNumber":'
                    suffix: '}'
                    commit_message: 'Increment the build number to '
            -   run: npm ci
            -   run: npm run build --if-present