name: Build

on:
    push:
        branches: [ "master" ]

jobs:
    build:
        
        runs-on: ubuntu-latest
        
        steps:
            -   uses: actions/checkout@v4
            -   name: Use Node.js ${{ matrix.node-version }}
                uses: actions/setup-node@v4
            -   name: Update version in package.json
                uses: maks-stupak/gh-action-bump-version@v7
            -   run: npm ci
            -   run: npm run build --if-present